

# Data Preprocessing of the dataset 'investment_data'

# Step1 : Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Step 2: Import data set

In [2]:
dataset=pd.read_csv('../Data/investment_data.csv')

In [3]:
dataset

Capital investment  Employee salary  Advertisement expenditure       City  \
0            165361.76        136897.80                  471784.10    Kolkata   
1            162610.26        151377.59                  443898.53  Bengaluru   
2            153454.07        101145.55                  407934.54    Chennai   
3            144384.97        118671.85                  383199.62    Kolkata   
4            142119.90         91391.77                  366168.42    Chennai   
5            131889.46         99814.71                  362861.36    Kolkata   
6            134628.02        147198.87                  127716.82  Bengaluru   
7            130310.69        145530.06                  323876.68    Chennai   
8            120555.08        148718.95                  311613.29    Kolkata   
9            123347.44        108679.17                  304981.62  Bengaluru   
10           101925.64        110594.11                  229160.95    Chennai   
11           100684.52         91790.61                  249744.55  Bengaluru   
12            93876.31        127320.38                  249839.44    Chennai   
13            92004.95        135495.07                  252664.93  Bengaluru   
14           119955.80        156547.42                  256512.92    Chennai   
15           114536.17        122616.84                  261776.23    Kolkata   
16            78025.67        121597.55                  264346.06  Bengaluru   
17            94669.72        145077.58                  282574.31    Kolkata   
18            91761.72        114175.79                  294919.57    Chennai   
19            86432.26        153514.11                       0.00    Kolkata   
20            76266.42        113867.30                  298664.47  Bengaluru   
21            78402.03        153773.43                  299737.29    Kolkata   
22            74007.12        122782.75                  303319.26    Chennai   
23            67545.09        105751.03                  304768.73    Chennai   
24            77056.57         99281.34                  140574.81    Kolkata   
25            64677.27        139553.16                  137962.62  Bengaluru   
26            75341.43        144135.98                  134050.07    Chennai   
27            72120.16        127864.55                  353183.81    Kolkata   
28            66064.08        182645.56                  118148.20    Chennai   
29            65618.04        153032.06                  107138.38    Kolkata   
30            62007.04        115641.28                   91131.24    Chennai   
31            61148.94        152701.92                   88218.23    Kolkata   
32            63421.42        129219.61                   46085.25  Bengaluru   
33            55506.51        103057.49                  214634.81    Chennai   
34            46438.63        157693.92                  210797.67  Bengaluru   
35            46026.58         85047.44                  205517.64    Kolkata   
36            28676.32        127056.21                  201126.82    Chennai   
37            44082.51         51283.14                  197029.42  Bengaluru   
38            20242.15         65947.93                  185265.10    Kolkata   
39            38571.07         82982.09                  174999.30  Bengaluru   
40            28766.89        118546.05                  172795.67  Bengaluru   
41            27905.48         84710.77                  164470.71    Chennai   
42            23653.49         96189.63                  148001.11  Bengaluru   
43            15518.29        127382.30                   35534.17    Kolkata   
44            22190.30        154806.14                   28334.72  Bengaluru   
45             1012.79        124153.04                    1903.93    Kolkata   
46             1328.02        115816.21                  297114.46    Chennai   
47               12.56        135426.92                       0.00  Bengaluru   
48              554.61         5174

# Step3: To create feature matrix and dependent variable vector

In [17]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [18]:
print(x)
print(y)

[[165361.76 136897.8 471784.1 'Kolkata']
 [162610.26 151377.59 443898.53 'Bengaluru']
 [153454.07 101145.55 407934.54 'Chennai']
 [144384.97 118671.85 383199.62 'Kolkata']
 [142119.9 91391.77 366168.42 'Chennai']
 [131889.46 99814.71 362861.36 'Kolkata']
 [134628.02 147198.87 127716.82 'Bengaluru']
 [130310.69 145530.06 323876.68 'Chennai']
 [120555.08 148718.95 311613.29 'Kolkata']
 [123347.44 108679.17 304981.62 'Bengaluru']
 [101925.64 110594.11 229160.95 'Chennai']
 [100684.52 91790.61 249744.55 'Bengaluru']
 [93876.31 127320.38 249839.44 'Chennai']
 [92004.95 135495.07 252664.93 'Bengaluru']
 [119955.8 156547.42 256512.92 'Chennai']
 [114536.17 122616.84 261776.23 'Kolkata']
 [78025.67 121597.55 264346.06 'Bengaluru']
 [94669.72 145077.58 282574.31 'Kolkata']
 [91761.72 114175.79 294919.57 'Chennai']
 [86432.26 153514.11 0.0 'Kolkata']
 [76266.42 113867.3 298664.47 'Bengaluru']
 [78402.03 153773.43 299737.29 'Kolkata']
 [74007.12 122782.75 303319.26 'Chennai']
 [67545.09 105751.03

In [6]:
y

array([192274.39, 191804.62, 191062.95, 182914.55, 166200.5 , 157003.68,
       156135.07, 155765.16, 152224.33, 149772.52, 146134.51, 144271.96,
       141598.08, 134319.91, 132615.21, 129929.6 , 127005.49, 125382.93,
       124279.46, 122789.42, 118486.59, 111325.58, 110364.81, 108746.55,
       108564.6 , 107416.9 , 105746.1 , 105020.87, 103294.94, 101017.2 ,
        99950.15,  97496.12,  97440.4 ,  96791.48,  96725.36,  96492.07,
        90720.75,  89961.7 ,  81241.62,  81018.32,  78252.47,  77811.39,
        71511.05,  69771.54,  65212.89,  64938.64,  49503.31,  42572.29,
        35685.97,  14693.96])

# Step4: Replace missing data

In [19]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,:3])
x[:,:3]=imputer.transform(x[:,:3])

In [20]:
x

array([[165361.76, 136897.8, 471784.1, 'Kolkata'],
       [162610.26, 151377.59, 443898.53, 'Bengaluru'],
       [153454.07, 101145.55, 407934.54, 'Chennai'],
       [144384.97, 118671.85, 383199.62, 'Kolkata'],
       [142119.9, 91391.77, 366168.42, 'Chennai'],
       [131889.46, 99814.71, 362861.36, 'Kolkata'],
       [134628.02, 147198.87, 127716.82, 'Bengaluru'],
       [130310.69, 145530.06, 323876.68, 'Chennai'],
       [120555.08, 148718.95, 311613.29, 'Kolkata'],
       [123347.44, 108679.17, 304981.62, 'Bengaluru'],
       [101925.64, 110594.11, 229160.95, 'Chennai'],
       [100684.52, 91790.61, 249744.55, 'Bengaluru'],
       [93876.31, 127320.38, 249839.44, 'Chennai'],
       [92004.95, 135495.07, 252664.93, 'Bengaluru'],
       [119955.8, 156547.42, 256512.92, 'Chennai'],
       [114536.17, 122616.84, 261776.23, 'Kolkata'],
       [78025.67, 121597.55, 264346.06, 'Bengaluru'],
       [94669.72, 145077.58, 282574.31, 'Kolkata'],
       [91761.72, 114175.79, 294919.57, 'Chen

# Step5: Encoding
# Feature matrix using  OneHotEncoding

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [22]:
x

array([[0.0, 0.0, 1.0, 165361.76, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162610.26, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153454.07, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144384.97, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142119.9, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131889.46, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134628.02, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130310.69, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120555.08, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123347.44, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101925.64, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100684.52, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93876.31, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 92004.95, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119955.8, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114536.17, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78025.67, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94669.72, 145077.5

# Dependent variable vector using label encoder

In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))

In [24]:
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
      dtype=int64)

# Step6: Splitting of data into training data set and testing data set

In [25]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)                              

In [26]:
xtest

array([[0.0, 0.0, 1.0, 72120.16, 127864.55, 353183.81],
       [0.0, 0.0, 1.0, 46026.58, 85047.44, 205517.64],
       [1.0, 0.0, 0.0, 28766.89, 118546.05, 172795.67],
       [0.0, 0.0, 1.0, 20242.15, 65947.93, 185265.1],
       [0.0, 1.0, 0.0, 153454.07, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144384.97, 118671.85, 383199.62],
       [0.0, 0.0, 1.0, 554.61, 51743.15, 0.0],
       [0.0, 0.0, 1.0, 65618.04, 153032.06, 107138.38],
       [0.0, 1.0, 0.0, 1328.02, 115816.21, 297114.46],
       [0.0, 0.0, 1.0, 61148.94, 152701.92, 88218.23]], dtype=object)

In [27]:
ytest

array([22, 14,  9, 11, 47, 46,  1, 20,  3, 18], dtype=int64)

# Step7: Feature scaling 

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,3:]=sc.fit_transform(xtrain[:,3:])
xtest[:,3:]=sc.fit_transform(xtest[:,3:])

In [29]:
xtrain

array([[1.0, 0.0, 0.0, -0.3213303849622652, 0.18700266744239274,
        -1.3700842498314485],
       [1.0, 0.0, 0.0, -0.8955888632549122, -1.6137113933587277,
        -0.28442172627772067],
       [0.0, 0.0, 1.0, 0.024851552213493347, 1.1432479184934816,
        0.7660716916733844],
       [0.0, 1.0, 0.0, -1.1242433521488782, 0.102749342455734,
        -0.06438621193773587],
       [0.0, 0.0, 1.0, 0.21041946816397133, 1.133148735616741,
        -1.758195776958278],
       [1.0, 0.0, 0.0, -1.2403142611108307, -1.0993455063779112,
        -0.5117896748200481],
       [1.0, 0.0, 0.0, -1.786624654615268, -0.2895193240547929,
        -1.377766348852932],
       [0.0, 1.0, 0.0, -0.04587483589220653, 0.7679187112767512,
        -0.6292797489632387],
       [0.0, 1.0, 0.0, -0.07670896217898561, -0.06367998831873588,
        0.7962376091160044],
       [1.0, 0.0, 0.0, 0.3391969091012882, 0.43139962169069607,
        0.36964711927627536],
       [0.0, 1.0, 0.0, -1.1420564374940387, -1.546388180

In [18]:
ytrain

array([17, 10, 28, 13, 30,  7,  0, 23, 27, 36,  8, 32,  4, 25, 26, 45, 16,
       35, 19, 39, 21,  5, 15, 31, 29, 24, 43, 42,  2, 48, 33, 49, 34, 44,
       38, 40, 41, 37,  6, 12], dtype=int64)

# Build a multiple linear model

In [19]:
from sklearn.linear_model import LinearRegression
regn=LinearRegression()
regn.fit(xtrain,ytrain)

LinearRegression()

In [20]:
yestimated=regn.predict(xtest)

In [21]:
print(yestimated)

[30.01158205 22.26888696 17.69685572 15.49475121 51.05597432 48.55924607
  9.27563715 26.94608678 11.696468   25.68977058]


In [22]:
print(ytest)

[22 14  9 11 47 46  1 20  3 18]


In [23]:
np.concatenate((yestimated.reshape(len(yestimated),1),yestimated.reshape(len(yestimated),1)),1)

array([[30.01158205, 30.01158205],
       [22.26888696, 22.26888696],
       [17.69685572, 17.69685572],
       [15.49475121, 15.49475121],
       [51.05597432, 51.05597432],
       [48.55924607, 48.55924607],
       [ 9.27563715,  9.27563715],
       [26.94608678, 26.94608678],
       [11.696468  , 11.696468  ],
       [25.68977058, 25.68977058]])

# Coefficient of the regressor

In [25]:
regn.coef_

array([-1.17234733e-01,  1.14000278e-01,  3.23445538e-03,  1.29240964e+01,
        1.38903961e-01,  7.99777571e-01])

In [40]:
regn.intercept_

25.85618518220345

In [26]:
print(regn.predict([[1,0,0,50661,115641,92496]]))

[744812.60822068]
